### ISSUE TITLE
Allow the user to browse a subtree while using the info command

### ISSUE THREAD

**Issue by badbeeker** [Nike-Inc/bartlett#33]
Currently you can browse the root tree by executing
`bartlett info /`

However it seems you can't do the same on a subtree
`bartlett info /folder/` or `bartlett info /folder/folder/`

Can we allow the same type of listing that is done for the subtree if it ends in a forward slash as we do for the root folder?

**Comment by dogonthehorizon** [comment]
Hey @badbeeker,

What error are you receiving when you attempt to execute `info` commands in sub-folders?

**Comment by badbeeker** [comment]
Jenkins was returning a 500 error and at first I thought it had to do with the request bartlett was sending. However, after upgrading the folder's plugin for our jenkins instance to 5.17, the issue is no longer reproducible.

I'm closing this issue.
